//
// Generated file, do not edit! Created by opp_msgc 4.4 from hamnhamh1.msg.
//

#ifndef _HAMNHAMH1_M_H_
#define _HAMNHAMH1_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>hamnhamh1.msg</tt> by opp_msgc.
 * <pre>
 * packet HamnhamnMsg1 {
 *     int source;
 *     string msg;
 *     int destination;
 * }
 * </pre>
 */
class HamnhamnMsg1 : public ::cPacket
{
  public:
    int source_var;
    opp_string msg_var;
    int destination_var;

  private:
    void copy(const HamnhamnMsg1& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HamnhamnMsg1&);

  public:
    HamnhamnMsg1(const char *name=NULL, int kind=0);
    HamnhamnMsg1(const HamnhamnMsg1& other);
    virtual ~HamnhamnMsg1();
    HamnhamnMsg1& operator=(const HamnhamnMsg1& other);
    virtual HamnhamnMsg1 *dup() const {return new HamnhamnMsg1(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual const char * getMsg() const;
    virtual void setMsg(const char * msg);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
};

inline void doPacking(cCommBuffer *b, HamnhamnMsg1& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, HamnhamnMsg1& obj) {obj.parsimUnpack(b);}


#endif // _HAMNHAMH1_M_H_
